version: "3.2"

services:

  monitor:
    build: .
    user: root
    volumes:
      - type: bind
        source: ./data
        target: /app/data
    command: pipenv run python3 ./src/monitor.py
    network_mode: host